mod depth_price_history;
use bigdecimal::BigDecimal;
use chrono::{NaiveDate, Utc};
pub use depth_price_history::DepthPriceHistory;
use reqwest::get;
use serde_json::Value;
use shared::{create_db_pool, run_migrations};
use sqlx::{Error, Row};
use std::str::FromStr;

#[tokio::main]
async fn main() {
    let pool = create_db_pool().await.expect(
        "Failed to create database pool. Ensure the database server is running and accessible.",
    );
    let pool = pool.lock().await;
    run_migrations(&pool).await.unwrap();
    let res = fetch_and_insert_data(&pool).await;
    if let Err(e) = res {
        eprintln!("Error: {:?}", e);
    }
}
async fn get_last_successful_entry_for_table(pool: &sqlx::PgPool, table_name: &str) -> i64 {
    let default_timestamp = NaiveDate::from_ymd_opt(2024, 10, 1)
        .unwrap_or_else(|| panic!("Invalid date"))
        .and_hms_opt(0, 0, 0)
        .unwrap()
        .timestamp();

    let query = format!(
        "SELECT COALESCE(MAX(endtime), $1) as last_successful_entry FROM {}",
        table_name
    );

    match sqlx::query(&query)
        .bind(default_timestamp)
        .fetch_one(pool)
        .await
    {
        Ok(row) => row
            .get::<Option<i64>, _>("last_successful_entry")
            .unwrap_or(default_timestamp),
        Err(_) => default_timestamp,
    }
}
async fn fetch_and_insert_data(pool: &sqlx::PgPool) -> Result<(), Error> {
    let mut from_time = get_last_successful_entry_for_table(&pool, "depth_price_history").await;
    // Set end time as the current time
    let end_time = Utc::now().timestamp();
    // println!("{:?}", end_time);
    // Loop to fetch data in chunks of 400
    loop {
        // Construct the API request URL with `from_time` and `count=400`
        let url = format!(
            "https://midgard.ninerealms.com/v2/history/depths/BTC.BTC?interval=hour&from={}&count=100", 
            from_time
        );
        println!("{:?}", url);
        // Make the API request
        let response: Value = get(&url).await.unwrap().json().await.unwrap();
        // println!("{:?}", response);
        if let Some(intervals) = response["intervals"].as_array() {
            // Loop through the data and insert each entry into the database
            for entry in intervals {
                let asset_price_history = DepthPriceHistory {
                    assetDepth: entry["assetDepth"]
                        .as_str()
                        .unwrap()
                        .parse::<i64>()
                        .unwrap(),
                    assetPrice: entry["assetPrice"]
                        .as_str()
                        .unwrap()
                        .parse::<f64>()
                        .unwrap(),
                    assetPriceUSD: entry["assetPriceUSD"]
                        .as_str()
                        .unwrap()
                        .parse::<f64>()
                        .unwrap(),
                    liquidityUnits: entry["liquidityUnits"]
                        .as_str()
                        .unwrap()
                        .parse::<i64>()
                        .unwrap(),
                    luvi: entry["luvi"].as_str().unwrap().parse::<f64>().unwrap(),
                    membersCount: entry["membersCount"]
                        .as_str()
                        .unwrap()
                        .parse::<i32>()
                        .unwrap(),
                    runeDepth: entry["runeDepth"].as_str().unwrap().parse::<i64>().unwrap(),
                    synthSupply: entry["synthSupply"]
                        .as_str()
                        .unwrap()
                        .parse::<i64>()
                        .unwrap(),
                    synthUnits: entry["synthUnits"]
                        .as_str()
                        .unwrap()
                        .parse::<i64>()
                        .unwrap(),
                    units: entry["units"].as_str().unwrap().parse::<i64>().unwrap(),
                    startTime: entry["startTime"].as_str().unwrap().parse::<i64>().unwrap(),
                    endTime: entry["endTime"].as_str().unwrap().parse::<i64>().unwrap(),
                    id: None, // This will be auto-generated by PostgreSQL
                };
                // println!("{:?}", asset_price_history);
                match sqlx::query!(
                    r#"
                    INSERT INTO Depth_Price_History (
                        assetDepth, assetPrice, assetPriceUSD, liquidityUnits, luvi,
                        membersCount, runeDepth, synthSupply, synthUnits, units, startTime, endTime
                    )
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
                    "#,
                    asset_price_history.assetDepth,
                    BigDecimal::from_str(&asset_price_history.assetPrice.to_string()).unwrap(),
                    BigDecimal::from_str(&asset_price_history.assetPriceUSD.to_string()).unwrap(),
                    asset_price_history.liquidityUnits,
                    BigDecimal::from_str(&asset_price_history.luvi.to_string()).unwrap(),
                    asset_price_history.membersCount,
                    asset_price_history.runeDepth,
                    asset_price_history.synthSupply,
                    asset_price_history.synthUnits,
                    asset_price_history.units,
                    asset_price_history.startTime,
                    asset_price_history.endTime
                )
                .execute(pool)
                .await
                {
                    Ok(_) => {}
                    Err(e) => {
                        if let sqlx::Error::Database(db_err) = &e {
                            if db_err.code() == Some("23505".into()) {
                                // Skip this entry due to duplicate key error
                                continue;
                            }
                        }
                        return Err(e);
                    }
                };
            }
            let last_entry = intervals.last().unwrap();
            let last_end_time = last_entry["endTime"]
                .as_str()
                .unwrap()
                .parse::<i64>()
                .unwrap();

            if last_end_time >= end_time {
                break;
            }

            from_time = last_end_time;
        } else {
            break;
        }
    }
    Ok(())
}
