[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version ="1.41.1", features = ["full"]}
sqlx = {version = "0.8.2", features = ["runtime-tokio-rustls", "macros", "postgres"]}
lazy_static = "1.5.0"
dotenvy = "0.15.7"

[lib]